(defalias 'sb 'speedbar)
(defalias 'fn 'cus-insert-buffer-file-name)
(defalias 'rb 'revert-buffer)
(defalias 'ts 'cus-insert-timestamp)
(defalias 'cls 'cus-clear-whitespace)
(defalias 'lcp 'cus-locate-project)
(defalias 'ctags 'cus-generate-tags)

(when (fboundp 'helm-locate) (defalias 'hlc 'helm-locate))
(when (fboundp 'helm-imenu) (defalias 'him 'helm-imenu))
(when (fboundp 'cus-say) (defalias 'say 'cus-say))
(when (fboundp 'cus-open-in-macvim) (defalias 'mvim 'cus-open-in-macvim))
(when (fboundp 'cus-paste-from-clipboard)
  (defalias 'pst 'cus-paste-from-clipboard))
(when (fboundp 'cus-copy-to-clipboard)
  (defalias 'cp 'cus-copy-to-clipboard))

(when (fboundp 'list-packages) (defalias 'lp 'list-packages))
